### ISSUE TITLE
svg 中的 image 元素无法在 iphone 以及 ipad 上显示

### ISSUE THREAD

**Issue by neal1991** [neal1991/subway-shanghai#11]
场景：
中转站使用的是 image 元素。链接的是 base64 图片，但是其在 IOS 设备 iphone 以及 ipad 上都无法显示，包括 chrome 浏览器以及 safari浏览器，目前不确定在 mac 上的显示情况，如果知道的话，还请告知。
目前尝试过的解决方法：
* 将 href 替换成 xlms:href
* 为 image 元素设置宽度和高度
* 为 svg 元素设置宽度和高度

以上方案都没有解决问题，怀疑很有可能还是和 IOS 设备有关，但目前仍未有其他的解决方法。

**Comment by wonyun** [comment]
还有解决办法么

**Comment by neal1991** [comment]
* 将 href 设置为 xlink:href
* 为 image 元素设置宽度和高度
