### ISSUE TITLE
localhost:3000

### ISSUE THREAD

**Issue by yeqqmatlab** [neal1991/subway-shanghai#15]
<div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
首页就这些，下一步是啥

**Comment by neal1991** [comment]
不明白你的意思，这不是我的 REDAME
